meta_product_name: "Call of Dirty"
meta_title: "Call of Dirty - Faîtes la chasse aux déchets mal triés !"
meta_description: "Relevant description"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@WahidKadri3"               # required for Twitter Cards
