meta_product_name: "Call of Dirty"
meta_title: "Call of Dirty - Faîtes la chasse aux déchets mal triés !"
meta_description: "Réduisez les erreurs de tri de manière ludique ! Scannez le code barre de votre produit et découvrez la benne de tri adaptée à chaque emballage !"
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@WahidKadri3"               # required for Twitter Cards
